[project]
name = "apex44-zero"
version = "10.0.0"
description = "Unkillable Text Protection - QAC 44/44 - Self-Root For Eternity"
authors = [{name="Amr Gad"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.urls]
Homepage = "https://github.com/agad70696-coder/apex44-zero"
