name: Fix all missing init
on: workflow_dispatch
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          find IRRE -name "init.py" -delete
          find IRRE -type d | while read dir; do
            if [ ! -f "$dir/__init__.py" ]; then
              echo "# V8 Module" > "$dir/__init__.py"
            fi
          done
          echo "# V8 Package" > IRRE/__init__.py
      - run: |
          git config --global user.name "fix-bot"
          git config --global user.email "fix@bot.com"
          git add .
          git commit -m "Fix all IRRE init" || true
          git push
