name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '17 4 * * 1'
  push:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Scorecard analysis
        uses: ossf/scorecard-action@<SCORECARD_FULL_COMMIT_SHA>
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@<CODEQL_FULL_COMMIT_SHA>
        with:
          sarif_file: results.sarif
